// apps/web/src/components/meal/DayAnalysisCard.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import type { DayAnalysis } from '@foodeez/shared';
import { aiService } from '@/services/aiService';
import { AIStreamError } from '@/services/aiStream';
import StreamingText from '@/components/ai/StreamingText.vue';
import { useMealStore } from '@/stores/meal';
import { scoreStroke, scoreTextClass } from '@/utils/analysisScore';

const props = defineProps<{
  userId: string;
  date: string;
  isToday: boolean;
}>();

const mealStore = useMealStore();

const analysis = ref<DayAnalysis | null>(null);
const isAnalyzing = ref(false);
const error = ref<string | null>(null);
/** What the model has written so far, shown while it writes. */
const streamedText = ref('');

/**
 * Changes whenever the day's meals do - which is exactly when the server retires the stored
 * analysis, so it is also when this card should go back and ask what is still on file.
 */
const daySignature = computed(() =>
  mealStore.dailyLogs
    .map(
      (log) =>
        `${log.mealType}:${log.items.map((item) => `${item.foodItem.id}x${item.quantity}`).join(',')}`,
    )
    .join('|'),
);

const dayLabel = computed(() => (props.isToday ? 'today' : 'this day'));

const scoreColor = computed(() => scoreStroke(analysis.value?.score ?? 0));
const scoreTextColor = computed(() => scoreTextClass(analysis.value?.score ?? 0));

const analyzedAt = computed(() =>
  analysis.value?.generatedAt
    ? new Date(analysis.value.generatedAt).toLocaleTimeString(undefined, {
        hour: 'numeric',
        minute: '2-digit',
      })
    : null,
);

/** Only reads what is already stored - never spends an AI call. */
async function loadStored() {
  analysis.value = null;
  error.value = null;

  if (!props.userId || mealStore.dailyLogs.length === 0) {
    return;
  }

  try {
    analysis.value = await aiService.getDayAnalysis(props.userId, props.date);
  } catch {
    analysis.value = null;
  }
}

async function runAnalysis(refresh: boolean) {
  if (!props.userId) {
    return;
  }

  isAnalyzing.value = true;
  error.value = null;
  streamedText.value = '';

  try {
    analysis.value = await aiService.analyzeDayStream(props.userId, props.date, refresh, (text) => {
      streamedText.value += text;
    });
  } catch (err: unknown) {
    error.value = err instanceof AIStreamError ? err.message : extractErrorMessage(err);
  } finally {
    isAnalyzing.value = false;
  }
}

function extractErrorMessage(err: unknown): string {
  if (err && typeof err === 'object' && 'response' in err) {
    const e = err as { response?: { data?: { message?: string; detail?: string; title?: string } } };
    return (
      e.response?.data?.message ??
      e.response?.data?.detail ??
      e.response?.data?.title ??
      'The analysis could not be completed. Please try again.'
    );
  }

  return 'The analysis could not be completed. Please try again.';
}

watch([() => props.date, () => props.userId, daySignature], loadStored, { immediate: true });
</script>

<template>
  <div
    class="rounded-2xl border border-purple-200 dark:border-purple-900 bg-purple-50 dark:bg-purple-950/40 p-4"
  >
    <div class="flex items-center justify-between gap-3">
      <p class="text-xs font-semibold uppercase tracking-wide text-purple-700 dark:text-purple-400">
        AI Day Analysis
      </p>
      <button
        v-if="analysis && !isAnalyzing"
        class="text-xs font-semibold text-purple-700 dark:text-purple-400 hover:underline"
        @click="runAnalysis(true)"
      >
        Re-run
      </button>
    </div>

    <div v-if="isAnalyzing" class="mt-3">
      <StreamingText :text="streamedText" :placeholder="`Reviewing ${dayLabel}'s meals...`" />
    </div>

    <template v-else-if="analysis">
      <div class="mt-3 flex items-start gap-3">
        <div class="relative h-16 w-16 shrink-0">
          <svg class="h-16 w-16 -rotate-90" viewBox="0 0 64 64">
            <circle cx="32" cy="32" r="28" fill="none" stroke="#e9d5ff" stroke-width="5" />
            <circle
              cx="32"
              cy="32"
              r="28"
              fill="none"
              :stroke="scoreColor"
              stroke-width="5"
              stroke-linecap="round"
              :stroke-dasharray="`${(analysis.score / 100) * 175.9} 175.9`"
            />
          </svg>
          <span
            class="absolute inset-0 flex items-center justify-center text-base font-bold"
            :class="scoreTextColor"
          >
            {{ analysis.score }}
          </span>
        </div>
        <div class="min-w-0">
          <p class="text-sm leading-snug text-gray-700 dark:text-gray-200">{{ analysis.status }}</p>
          <p v-if="analyzedAt" class="mt-1 text-xs text-gray-400">Analyzed at {{ analyzedAt }}</p>
        </div>
      </div>

      <div v-if="analysis.gaps.length > 0" class="mt-3">
        <p class="mb-1.5 text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-gray-400">
          Still short on
        </p>
        <div class="flex flex-wrap gap-1.5">
          <span
            v-for="gap in analysis.gaps"
            :key="gap"
            class="rounded-full bg-red-100 dark:bg-red-900/40 px-2 py-0.5 text-xs font-medium text-red-700 dark:text-red-300"
          >
            {{ gap }}
          </span>
        </div>
      </div>

      <div v-if="analysis.recommendations.length > 0" class="mt-3">
        <p class="mb-1.5 text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-gray-400">
          {{ isToday ? 'What to have next' : 'What would have rounded it out' }}
        </p>
        <ul class="space-y-1">
          <li
            v-for="recommendation in analysis.recommendations"
            :key="recommendation"
            class="flex items-start gap-1.5 text-sm text-gray-700 dark:text-gray-200"
          >
            <span class="mt-0.5 shrink-0 text-green-500">&gt;</span>{{ recommendation }}
          </li>
        </ul>
      </div>
    </template>

    <template v-else>
      <p class="mt-2 text-sm text-gray-600 dark:text-gray-300">
        See how {{ dayLabel }}'s meals stack up against your targets, and what to eat to finish the
        day balanced.
      </p>
      <button
        class="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border-2 border-dashed border-purple-300 dark:border-purple-800 py-2 text-sm font-semibold text-purple-700 dark:text-purple-400 transition-colors hover:bg-purple-100 dark:hover:bg-purple-900/40"
        @click="runAnalysis(false)"
      >
        Analyze {{ dayLabel }}'s meals
      </button>
    </template>

    <p v-if="error" class="mt-3 text-sm text-red-600 dark:text-red-400">{{ error }}</p>
  </div>
</template>

// apps/mobile/src/components/meal/DayAnalysisCard.tsx
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import Svg, { Circle } from 'react-native-svg';
import { FontSize, FontWeight, Spacing, BorderRadius } from '@/constants/theme';
import { AIPanelDark, AIPanelLight, type AIPanelColors } from '@/constants/aiPanel';
import { useTheme, useThemeMode, type Palette } from '@/theme';
import { scoreColor } from '@foodeez/shared';
import { getDayAnalysis, analyzeDayStream } from '@/services/aiService';
import { AIStreamError } from '@/services/aiStream';
import type { DayAnalysisDto, MealLogDto } from '@/types';

const RADIUS = 28;
const CIRCUMFERENCE = 2 * Math.PI * RADIUS;

/**
 * How a day's meals stand against that day's targets, and what would round it out. Only
 * reads what is already stored when the day's meals change; generating a fresh one is
 * always the reader's own choice, since it spends an AI call.
 */
export function DayAnalysisCard({
  userId,
  date,
  dailyLogs,
  isToday,
}: {
  userId: string;
  date: string;
  dailyLogs: MealLogDto[];
  isToday: boolean;
}) {
  const C = useTheme();
  const { scheme } = useThemeMode();
  const AI = scheme === 'dark' ? AIPanelDark : AIPanelLight;
  const styles = useMemo(() => makeStyles(C, AI), [C, AI]);

  const [analysis, setAnalysis] = useState<DayAnalysisDto | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [streamedText, setStreamedText] = useState('');
  const request = useRef<{ cancel: () => void } | null>(null);

  // Changes whenever the day's meals do - which is exactly when the server retires the
  // stored analysis, so it is also when this card should go back and ask what is on file.
  const daySignature = dailyLogs
    .map((log) => `${log.mealType}:${log.items.map((item) => `${item.foodItem.id}x${item.quantity}`).join(',')}`)
    .join('|');

  useEffect(() => {
    let cancelled = false;
    setAnalysis(null);
    setError(null);

    if (!userId || dailyLogs.length === 0) {
      return;
    }

    getDayAnalysis(userId, date)
      .then((result) => {
        if (!cancelled) setAnalysis(result);
      })
      .catch(() => {
        if (!cancelled) setAnalysis(null);
      });

    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId, date, daySignature, dailyLogs.length]);

  useEffect(() => () => request.current?.cancel(), []);

  if (dailyLogs.length === 0) {
    return null;
  }

  const dayLabel = isToday ? 'today' : 'this day';

  const runAnalysis = (refresh: boolean) => {
    if (isAnalyzing) {
      return;
    }

    setIsAnalyzing(true);
    setError(null);
    setStreamedText('');

    const onDelta = (text: string) => setStreamedText((prev) => prev + text);
    const streaming = analyzeDayStream(userId, date, refresh, onDelta);
    request.current = streaming;

    streaming
      .then(setAnalysis)
      .catch((err: unknown) => {
        setError(err instanceof AIStreamError ? err.message : 'The analysis could not be completed. Please try again.');
      })
      .finally(() => {
        request.current = null;
        setIsAnalyzing(false);
      });
  };

  const analyzedAt = analysis?.generatedAt
    ? new Date(analysis.generatedAt).toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })
    : null;

  return (
    <View style={styles.card}>
      <View style={styles.headerRow}>
        <Text style={styles.headerLabel}>AI Day Analysis</Text>
        {analysis && !isAnalyzing && (
          <TouchableOpacity onPress={() => runAnalysis(true)}>
            <Text style={styles.rerun}>Re-run</Text>
          </TouchableOpacity>
        )}
      </View>

      {isAnalyzing && (
        <Text style={styles.streamText}>
          {streamedText.length > 0 ? streamedText : `Reviewing ${dayLabel}'s meals...`}
        </Text>
      )}

      {!isAnalyzing && error && <Text style={styles.errorText}>{error}</Text>}

      {!isAnalyzing && !error && analysis && (
        <>
          <View style={styles.headRow}>
            <View style={styles.ringWrap}>
              <Svg width={64} height={64} viewBox="0 0 64 64">
                <Circle cx={32} cy={32} r={RADIUS} stroke={AI.ringTrack} strokeWidth={5} fill="none" />
                <Circle
                  cx={32}
                  cy={32}
                  r={RADIUS}
                  stroke={scoreColor(analysis.score)}
                  strokeWidth={5}
                  fill="none"
                  strokeLinecap="round"
                  strokeDasharray={`${(analysis.score / 100) * CIRCUMFERENCE} ${CIRCUMFERENCE}`}
                  rotation={-90}
                  origin="32, 32"
                />
              </Svg>
              <Text style={[styles.ringScore, { color: scoreColor(analysis.score) }]}>{analysis.score}</Text>
            </View>
            <View style={styles.flex}>
              <Text style={styles.status}>{analysis.status}</Text>
              {analyzedAt && <Text style={styles.analyzedAt}>Analyzed at {analyzedAt}</Text>}
            </View>
          </View>

          {analysis.gaps.length > 0 && (
            <View style={styles.section}>
              <Text style={styles.sectionLabel}>Still short on</Text>
              <View style={styles.tagRow}>
                {analysis.gaps.map((gap) => (
                  <View key={gap} style={styles.gapTag}>
                    <Text style={styles.gapTagText}>{gap}</Text>
                  </View>
                ))}
              </View>
            </View>
          )}

          {analysis.recommendations.length > 0 && (
            <View style={styles.section}>
              <Text style={styles.sectionLabel}>
                {isToday ? 'What to have next' : 'What would have rounded it out'}
              </Text>
              {analysis.recommendations.map((recommendation) => (
                <Text key={recommendation} style={styles.recommendation}>
                  {'> '}
                  {recommendation}
                </Text>
              ))}
            </View>
          )}
        </>
      )}

      {!isAnalyzing && !analysis && !error && (
        <TouchableOpacity style={styles.button} onPress={() => runAnalysis(false)}>
          {isAnalyzing ? (
            <ActivityIndicator size="small" color={C.secondary} />
          ) : (
            <Text style={styles.buttonIcon}>*</Text>
          )}
          <Text style={styles.buttonText}>Analyze {dayLabel}&apos;s meals</Text>
        </TouchableOpacity>
      )}
    </View>
  );
}

const makeStyles = (C: Palette, AI: AIPanelColors) =>
  StyleSheet.create({
    flex: { flex: 1 },
    card: {
      borderRadius: BorderRadius.lg,
      borderWidth: 1,
      borderColor: AI.panelBorder,
      backgroundColor: AI.panelBg,
      padding: Spacing.md,
      gap: Spacing.sm,
    },
    headerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    headerLabel: {
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: AI.accentText,
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    rerun: { fontSize: FontSize.xs, fontWeight: FontWeight.semibold, color: AI.accentText },
    streamText: { fontSize: FontSize.sm, color: C.textSecondary, lineHeight: 20 },
    errorText: { fontSize: FontSize.sm, color: C.error },
    headRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
    ringWrap: { width: 64, height: 64, alignItems: 'center', justifyContent: 'center' },
    ringScore: { position: 'absolute', fontSize: FontSize.md, fontWeight: FontWeight.bold },
    status: { fontSize: FontSize.sm, color: C.text, lineHeight: 19 },
    analyzedAt: { fontSize: FontSize.xs, color: C.textSecondary, marginTop: 4 },
    section: { gap: 4 },
    sectionLabel: {
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: C.textSecondary,
      letterSpacing: 0.3,
      textTransform: 'uppercase',
    },
    tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    gapTag: {
      borderRadius: BorderRadius.full,
      backgroundColor: AI.tagBg,
      paddingHorizontal: Spacing.sm,
      paddingVertical: 3,
    },
    gapTagText: { fontSize: FontSize.xs, fontWeight: FontWeight.medium, color: AI.tagText },
    recommendation: { fontSize: FontSize.sm, color: C.text, lineHeight: 19 },
    button: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.xs,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: AI.buttonBorder,
      borderRadius: BorderRadius.lg,
      paddingVertical: Spacing.sm,
    },
    buttonIcon: { fontSize: FontSize.md, color: C.secondary },
    buttonText: { fontSize: FontSize.sm, fontWeight: FontWeight.semibold, color: AI.accentText },
  });
