// apps/web/src/components/meal/MealSection.vue
<script setup lang="ts">
import { ref } from 'vue';
import { MealType, MEAL_TYPE_LABELS } from '@foodeez/shared';
import type { MealLog, MealLogItem, NutritionalInfo } from '@foodeez/shared';
import FoodItemRow from './FoodItemRow.vue';
import MealAnalysisBadge from './MealAnalysisBadge.vue';

interface Props {
  mealLog: MealLog;
  mealType: MealType;
  items: MealLogItem[];
  totalNutrition: NutritionalInfo;
}

defineProps<Props>();
const emit = defineEmits<{ editMeal: [mealLog: MealLog]; deleteMeal: [mealLog: MealLog] }>();

const isCollapsed = ref(false);

const mealIcons: Record<MealType, string> = {
  [MealType.Breakfast]: 'Breakfast',
  [MealType.MorningSnack]: 'Snack',
  [MealType.Lunch]: 'Lunch',
  [MealType.AfternoonSnack]: 'Snack',
  [MealType.Dinner]: 'Dinner',
  [MealType.EveningSnack]: 'Evening',
};
</script>

<template>
  <div class="overflow-hidden rounded-xl border border-gray-100 dark:border-gray-800 bg-white dark:bg-gray-900">
    <div class="flex items-center justify-between px-4 py-3 transition-colors hover:bg-gray-50 dark:hover:bg-gray-800">
      <div class="flex items-center gap-2">
        <span class="text-sm font-semibold text-gray-500 dark:text-gray-400">{{ mealIcons[mealType] ?? 'Meal' }}</span>
        <span class="text-sm font-semibold text-gray-800 dark:text-gray-100">
          {{ MEAL_TYPE_LABELS[mealType] ?? `Meal ${mealType}` }}
        </span>
        <span class="rounded-full bg-gray-100 dark:bg-gray-800 px-2 py-0.5 text-xs text-gray-400">
          {{ items.length }} item{{ items.length !== 1 ? 's' : '' }}
        </span>
        <!-- Only for a meal that already has an analysis stored: this reads what is on file
             and never spends an AI call, so it is safe to show on every row. -->
        <MealAnalysisBadge
          v-if="mealLog.analysis"
          :analysis="mealLog.analysis"
          :meal-type="mealType"
        />
      </div>
      <div class="flex items-center gap-3">
        <span class="text-sm font-semibold text-green-700 dark:text-green-400">
          {{ Math.round(totalNutrition.calories) }} kcal
        </span>
        <button
          class="text-xs font-medium text-green-700 dark:text-green-400 hover:text-green-800 dark:hover:text-green-300"
          @click.stop="emit('editMeal', mealLog)"
        >
          Edit
        </button>
        <button
          class="text-xs font-medium text-red-500 dark:text-red-400 hover:text-red-600 dark:hover:text-red-400"
          @click.stop="emit('deleteMeal', mealLog)"
        >
          Delete
        </button>
        <button
          class="rounded p-1 text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700"
          @click="isCollapsed = !isCollapsed"
        >
          <svg
            :class="['h-4 w-4 transition-transform', isCollapsed ? '-rotate-90' : '']"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
          </svg>
        </button>
      </div>
    </div>

    <div v-if="!isCollapsed">
      <div v-if="items.length === 0" class="px-4 py-3 text-sm italic text-gray-400">
        No items logged for this meal.
      </div>
      <div v-else class="divide-y divide-gray-50">
        <FoodItemRow
          v-for="item in items"
          :key="item.id"
          :item="item"
          class="px-1"
        />
      </div>

      <div v-if="items.length > 0" class="flex gap-4 bg-gray-50 dark:bg-gray-800 px-4 py-2 text-xs text-gray-500 dark:text-gray-400">
        <span>P: {{ Math.round(totalNutrition.protein) }}g</span>
        <span>C: {{ Math.round(totalNutrition.carbohydrates) }}g</span>
        <span>F: {{ Math.round(totalNutrition.fat) }}g</span>
      </div>
    </div>
  </div>
</template>

// apps/mobile/src/components/meal/MealSection.tsx
import React, { useState } from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { MealLogItemRow } from './MealLogItemRow';
import { FontSize, FontWeight, Spacing, BorderRadius } from '@/constants/theme';
import { useTheme, useThemedStyles, type Palette } from '@/theme';
import { scoreColor } from '@/utils/analysisScore';
import { MealType, type MealLogDto } from '@/types';

interface MealSectionProps {
  mealLog: MealLogDto;
  onEditMeal?: (mealLog: MealLogDto) => void;
  onDeleteMeal?: (mealLog: MealLogDto) => void;
}

const MEAL_TYPE_LABELS: Record<MealType, string> = {
  [MealType.Breakfast]: 'Breakfast',
  [MealType.MorningSnack]: 'Morning Snack',
  [MealType.Lunch]: 'Lunch',
  [MealType.AfternoonSnack]: 'Afternoon Snack',
  [MealType.Dinner]: 'Dinner',
  [MealType.EveningSnack]: 'Evening Snack',
};

const MEAL_TYPE_ICONS: Record<MealType, keyof typeof Ionicons.glyphMap> = {
  [MealType.Breakfast]: 'sunny-outline',
  [MealType.MorningSnack]: 'cafe-outline',
  [MealType.Lunch]: 'restaurant-outline',
  [MealType.AfternoonSnack]: 'nutrition-outline',
  [MealType.Dinner]: 'moon-outline',
  [MealType.EveningSnack]: 'ice-cream-outline',
};

export function MealSection({ mealLog, onEditMeal, onDeleteMeal }: MealSectionProps) {
  const C = useTheme();
  const styles = useThemedStyles(makeStyles);
  const [isExpanded, setIsExpanded] = useState(true);

  const calories = Math.round(mealLog.totalNutrition.calories);
  const label = MEAL_TYPE_LABELS[mealLog.mealType] ?? mealLog.mealType;
  const icon = MEAL_TYPE_ICONS[mealLog.mealType] ?? 'restaurant-outline';

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity
          style={styles.headerMain}
          onPress={() => setIsExpanded((prev) => !prev)}
          activeOpacity={0.7}
        >
          <View style={styles.headerLeft}>
            <View style={styles.iconBadge}>
              <Ionicons name={icon} size={16} color={C.primary} />
            </View>
            <View>
              <View style={styles.mealLabelRow}>
                <Text style={styles.mealLabel}>{label}</Text>
                {/* Only for a meal that already has an analysis stored: this reads what is
                    on file and never spends an AI call, so it is safe on every row. */}
                {mealLog.analysis && (
                  <View
                    style={[
                      styles.scoreBadge,
                      { borderColor: scoreColor(mealLog.analysis.score) },
                    ]}
                  >
                    <Text style={[styles.scoreBadgeText, { color: scoreColor(mealLog.analysis.score) }]}>
                      {mealLog.analysis.score}
                    </Text>
                  </View>
                )}
              </View>
              <Text style={styles.itemCount}>
                {mealLog.items.length} item{mealLog.items.length !== 1 ? 's' : ''}
              </Text>
            </View>
          </View>
          <View style={styles.headerRight}>
            <Text style={styles.calories}>{calories} kcal</Text>
            <Ionicons
              name={isExpanded ? 'chevron-up' : 'chevron-down'}
              size={20}
              color={C.textSecondary}
            />
          </View>
        </TouchableOpacity>
        <View style={styles.actions}>
          <TouchableOpacity onPress={() => onEditMeal?.(mealLog)} hitSlop={8}>
            <Text style={styles.editAction}>Edit</Text>
          </TouchableOpacity>
          <TouchableOpacity onPress={() => onDeleteMeal?.(mealLog)} hitSlop={8}>
            <Text style={styles.deleteAction}>Delete</Text>
          </TouchableOpacity>
        </View>
      </View>

      {isExpanded && (
        <View style={styles.itemsList}>
          {mealLog.items.map((item) => (
            <MealLogItemRow key={item.id} item={item} />
          ))}
        </View>
      )}
    </View>
  );
}

const makeStyles = (C: Palette) => StyleSheet.create({
  container: {
    backgroundColor: C.surface,
    borderRadius: 12,
    marginBottom: Spacing.sm,
    overflow: 'hidden',
  },
  header: {
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.sm,
  },
  headerMain: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  iconBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: C.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mealLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  mealLabel: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.semibold,
    color: C.text,
  },
  scoreBadge: {
    borderWidth: 1.5,
    borderRadius: BorderRadius.full,
    paddingHorizontal: 6,
    paddingVertical: 1,
  },
  scoreBadgeText: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
  },
  itemCount: {
    fontSize: FontSize.sm,
    color: C.textSecondary,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  calories: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.semibold,
    color: C.primary,
  },
  actions: {
    flexDirection: 'row',
    gap: Spacing.md,
    justifyContent: 'flex-end',
    marginTop: Spacing.sm,
  },
  editAction: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.medium,
    color: C.primary,
  },
  deleteAction: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.medium,
    color: C.error,
  },
  itemsList: {
    borderTopWidth: 1,
    borderTopColor: C.divider,
  },
});
